[private]
@default:
  just --list --unsorted

# === Development ===

# Add all and commit
[no-cd]
commit:
  #!/usr/bin/env bash

  cd $(git rev-parse --show-toplevel)
  git add .
  git commit

# Add all and amend
[no-cd]
amend:
  #!/usr/bin/env bash

  cd $(git rev-parse --show-toplevel)
  git add .
  git commit --amend --no-edit

# Lint Go project
[no-cd]
@lint-go:
  go vet ./...
  golangci-lint run ./...

# === System update ===

# Update system
update:
  #!/usr/bin/env bash

  if command -v dnf &>/dev/null; then
    sudo dnf upgrade -y
    sudo dnf autoremove -y
  elif command -v nala &>/dev/null; then
    # Package install
    sudo nala update
    sudo nala full-upgrade -y

    # Clean up
    sudo nala autopurge -y
    sudo nala clean
  else
    gum style --foreground 1 "Could not find dnf nor nala!"
  fi

  command -v flatpak &>/dev/null && flatpak update -y

  if command -v brew &>/dev/null; then
    brew update -y
    brew upgrade -y
    brew cleanup
  else
    gum style --foreground 1 "brew not found"
  fi

  if command -v mise &>/dev/null; then
    mise up
  else
    gum style --foreground 1 "mise not found"
  fi

  if command -v bin &>/dev/null; then
    bin update -y
    bin prune
  else
    gum style --foreground 1 "bin not found"
  fi

  # Update dotfiles
  { cd ~/.dotfiles && git pull; } || gum style --foreground 1 "Could not update dotfiles"

  just check-fedora-system-update
alias up := update

# Check if there is a new system release
check-fedora-system-update:
  #!/usr/bin/env bash
  
  # Only works for fedora
  grep -iq 'fedora' /etc/os-release || exit 0

  CURRENT=$(rpm -E %fedora)
  LATEST=$(curl -s "https://endoflife.date/api/fedora.json" | jq -r '.[0].cycle')

  if [ "$LATEST" -gt "$CURRENT" ]; then
    gum style --foreground 3 "New release available: Fedora $LATEST (current: $CURRENT)"
  else
    gum style --foreground 2 "On latest stable OS release: Fedora $CURRENT"
  fi

# === Notification ===

ping $message='Ping':
  #!/usr/bin/env bash

  curl -Ss -X POST "https://api.telegram.org/bot$(kv get bot-token@telegram)/sendMessage" \
    -d chat_id=$(kv get chat-id@telegram) \
    -d text="$DEVICE_NAME: $message" >/dev/null
