[custom0]
binding='<Super>c'
command='kitty'
name='Start Terminal'

[custom1]
binding='<Super>v'
command='vivaldi'
name='Vivaldi'

[custom2]
binding='<Super>e'
command='nautilus'
name='Files Explorer'
